apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secaudit.fullname" . }}
  labels:
    {{- include "secaudit.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "secaudit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "secaudit.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "secaudit.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - secaudit
          - audit
          - --profile
          - {{ index .Values.config.profiles 0 }}
          - --level
          - {{ .Values.config.level }}
          - --workers
          - "{{ .Values.config.workers }}"
        env:
          - name: SECAUDIT_LEVEL
            value: {{ .Values.config.level }}
          - name: SECAUDIT_WORKERS
            value: "{{ .Values.config.workers }}"
        {{- if .Values.healthCheck.enabled }}
        livenessProbe:
          exec:
            command:
              - secaudit
              - health
              - --type
              - liveness
              - --json
          initialDelaySeconds: {{ .Values.healthCheck.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.healthCheck.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.healthCheck.liveness.failureThreshold }}
        readinessProbe:
          exec:
            command:
              - secaudit
              - health
              - --type
              - readiness
              - --json
          initialDelaySeconds: {{ .Values.healthCheck.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthCheck.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.healthCheck.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.healthCheck.readiness.failureThreshold }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          {{- if .Values.persistence.enabled }}
          - name: results
            mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
          {{- if .Values.hostPaths.enabled }}
          {{- range .Values.hostPaths.paths }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            readOnly: {{ .readOnly }}
          {{- end }}
          {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: results
          persistentVolumeClaim:
            claimName: {{ include "secaudit.fullname" . }}
        {{- end }}
        {{- if .Values.hostPaths.enabled }}
        {{- range .Values.hostPaths.paths }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: Directory
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
