{{- if .Values.encryption.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secaudit.fullname" . }}-encryption
  labels:
    {{- include "secaudit.labels" . | nindent 4 }}
    app.kubernetes.io/component: encryption
type: Opaque
data:
  {{- if .Values.encryption.gpg.publicKey }}
  gpg-public-key: {{ .Values.encryption.gpg.publicKey | b64enc }}
  {{- end }}
  {{- if .Values.encryption.gpg.privateKey }}
  gpg-private-key: {{ .Values.encryption.gpg.privateKey | b64enc }}
  {{- end }}
  {{- if .Values.encryption.gpg.passphrase }}
  gpg-passphrase: {{ .Values.encryption.gpg.passphrase | b64enc }}
  {{- end }}
  {{- if .Values.encryption.aes.key }}
  aes-key: {{ .Values.encryption.aes.key | b64enc }}
  {{- end }}
{{- end }}

{{- if .Values.authentication.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secaudit.fullname" . }}-auth
  labels:
    {{- include "secaudit.labels" . | nindent 4 }}
    app.kubernetes.io/component: authentication
type: Opaque
data:
  {{- if .Values.authentication.jwt.secret }}
  jwt-secret: {{ .Values.authentication.jwt.secret | b64enc }}
  {{- end }}
  {{- if .Values.authentication.oidc.clientSecret }}
  oidc-client-secret: {{ .Values.authentication.oidc.clientSecret | b64enc }}
  {{- end }}
  {{- range .Values.authentication.apiKeys.keys }}
  {{- if .key }}
  api-key-{{ .name }}: {{ .key | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}

{{- if .Values.tls.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secaudit.fullname" . }}-tls
  labels:
    {{- include "secaudit.labels" . | nindent 4 }}
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certificate | b64enc }}
  tls.key: {{ .Values.tls.privateKey | b64enc }}
  {{- if .Values.tls.ca }}
  ca.crt: {{ .Values.tls.ca | b64enc }}
  {{- end }}
{{- end }}

{{- if .Values.externalSecrets.enabled -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "secaudit.fullname" . }}-external
  labels:
    {{- include "secaudit.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: {{ .Values.externalSecrets.secretStoreKind | default "SecretStore" }}
  
  target:
    name: {{ include "secaudit.fullname" . }}-external-data
    creationPolicy: Owner
  
  data:
    {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        {{- if .property }}
        property: {{ .property }}
        {{- end }}
    {{- end }}
{{- end }}

{{- if .Values.vault.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "secaudit.fullname" . }}-vault
  labels:
    {{- include "secaudit.labels" . | nindent 4 }}
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: {{ .Values.vault.role }}
    vault.hashicorp.com/agent-inject-secret-config: {{ .Values.vault.secretPath }}
    vault.hashicorp.com/agent-inject-template-config: |
      {{`{{- with secret "`}}{{ .Values.vault.secretPath }}{{`" -}}
      export GPG_PASSPHRASE="{{ .Data.data.gpg_passphrase }}"
      export JWT_SECRET="{{ .Data.data.jwt_secret }}"
      export AES_KEY="{{ .Data.data.aes_key }}"
      {{- end }}`}}
{{- end }}
