name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Имя тэга (например v0.1.1)"
        required: false

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag_step.outputs.tag_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve tag
        id: tag_step
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG_NAME="${{ github.ref_name }}"
          else
            TAG_NAME="${{ github.event.inputs.tag }}"
          fi
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
          if [ -z "${TAG_NAME}" ]; then echo "Tag name is empty" >&2; exit 1; fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install build twine

      - name: Build sdist/wheel
        run: |
          python -m build
          sha256sum dist/* > dist/SHA256SUMS.txt
          ls -lah dist

      - name: Check package
        run: |
          twine check dist/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: secaudit-${{ steps.tag_step.outputs.tag_name }}
          path: |
            dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          name: secaudit-${{ needs.build.outputs.tag_name }}
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.tag_name }}
          name: Release ${{ needs.build.outputs.tag_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/*
